<a href="https://colab.research.google.com/github/khangsheng1/PyTorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [24]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [8]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
# Subtraction
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [10]:
# Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [11]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
# Mul Function
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Div Function
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
# Remainder Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents / Power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [19]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
# Exponent Longhand
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

# **Reassignment**

In [21]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([1, 2, 3, 4])

In [26]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])