<a href="https://colab.research.google.com/github/khangsheng1/PyTorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# **LISTS**

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [9]:
my_array = np.random.rand(3,4)
my_array

array([[0.9789701 , 0.3123503 , 0.16676219, 0.13746314],
       [0.73843761, 0.76300493, 0.22580397, 0.87128921],
       [0.32850976, 0.29008318, 0.91635185, 0.60621734]])

In [10]:
my_array.dtype

dtype('float64')

# **Tensor**

In [11]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.6763, 0.5561, 0.3186, 0.7753],
        [0.4925, 0.0116, 0.2956, 0.3045],
        [0.3109, 0.7013, 0.8259, 0.5552]])

In [14]:
tensor_2d.dtype

torch.float32

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
## Create tensor out of numpy array
my_tensor = torch.tensor(my_array)
my_tensor

tensor([[0.9790, 0.3124, 0.1668, 0.1375],
        [0.7384, 0.7630, 0.2258, 0.8713],
        [0.3285, 0.2901, 0.9164, 0.6062]], dtype=torch.float64)